const sections = [
  ['1. Who We Are', <>Gabitor AI is operated by <strong>K.R.&G.M. CLEANING LLC</strong> ("Gabitor," "we," "us," or "our"). Our business address is 5250 Old Orchard Rd, Suite 300, Skokie, IL 60077-4462, United States.</>],
  ['2. Information We Collect', <>We collect account information you provide, such as your email address. We collect the prompts, settings, and generated content needed to provide the Studio. We may also collect limited technical and usage information, such as log data, device and browser information, and security-related data.</>],
  ['3. How We Use Information', <>We use information to create and deliver requested content, authenticate accounts, administer credits, maintain security, prevent fraud or misuse, respond to requests, and improve the Service. We do not sell your personal information.</>],
  ['4. Service Providers', <>We use providers for hosting, authentication, storage, and cloud-based AI processing. These providers may process information only as needed to provide services to us. Generated content is processed to fulfill your request.</>],
  ['5. Retention and Security', <>We retain information only for as long as reasonably necessary for the purposes described here, including security, legal, and operational needs. No system is completely secure, but we use reasonable technical and organizational safeguards designed to protect information.</>],
  ['6. Your Choices', <>You may request access to, correction of, or deletion of account-related personal information, subject to applicable law and legitimate business requirements. To make a request, write to us at the address in Section 1. You may also stop using the Service and delete your account where that option is available.</>],
  ['7. Children', <>Gabitor AI is not directed to children under 13, and we do not knowingly collect personal information from children under 13. If you believe a child has provided us personal information, contact us at the address above so we can address the request.</>],
  ['8. Changes and Contact', <>We may update this Privacy Policy as the Service changes. The updated version will be posted here with a revised effective date. Questions about this Policy may be sent by mail to K.R.&G.M. CLEANING LLC, 5250 Old Orchard Rd, Suite 300, Skokie, IL 60077-4462, United States.</>]
];

export default function PrivacyPolicy() {
 return <main style={{maxWidth:820,margin:'0 auto',padding:'72px 24px',color:'#edf0ff',lineHeight:1.7}}><a href="/" style={{color:'#b9a7ff',textDecoration:'none'}}>← Back to Gabitor</a><p style={{letterSpacing:'0.14em',fontSize:12,color:'#b9a7ff',marginTop:40}}>GABITOR AI</p><h1 style={{fontSize:48,lineHeight:1.1,margin:'8px 0 12px'}}>Privacy Policy</h1><p style={{color:'#aab0c5'}}>Effective date: September 9, 2026</p><p>This Privacy Policy explains how Gabitor AI handles personal information when you visit or use our website, account services, and AI creative tools (the "Service").</p>{sections.map(([title,body])=><section key={title} style={{marginTop:34}}><h2 style={{fontSize:23}}>{title}</h2><p>{body}</p></section>)}<p style={{marginTop:48,fontSize:14,color:'#aab0c5'}}>This policy is intended to describe our current practices in plain language. It is not a substitute for individualized legal advice.</p></main>;
}
