const sections = [
  ['1. Agreement to These Terms', <>These Terms of Service ("Terms") govern your access to and use of Gabitor AI (the "Service"), operated by <strong>K.R.&G.M. CLEANING LLC</strong>, 5250 Old Orchard Rd, Suite 300, Skokie, IL 60077-4462, United States. By creating an account or using the Service, you agree to these Terms.</>],
  ['2. Accounts and Access', <>You must create an account and provide accurate information to use image generation. You are responsible for protecting your account credentials and for activity under your account. You must be at least 13 years old to use the Service. We may suspend or restrict access where we reasonably believe there is fraud, abuse, a security risk, or a violation of these Terms.</>],
  ['3. Credits and Paid Features', <>Generation features may require credits. Where credits are offered or sold, the applicable price, amount, and limits will be shown before purchase or use. Credits have no cash value and are not transferable except where required by law. We may change future credit offerings or prices with notice on the Service.</>],
  ['4. Strict Content Policy and Acceptable Use', <>Gabitor has a zero-tolerance policy for sexual, nude, pornographic, adult, exploitative, minor-related, or non-consensual content, including intimate deepfakes of identifiable people. You may not attempt to create, request, upload, distribute, or circumvent safeguards for such material. You may not use the Service to violate law, infringe intellectual-property or privacy rights, create harmful, deceptive, hateful, or fraudulent material, bypass access controls, automate excessive requests, reverse engineer the Service, or interfere with its security or operation.</>],
  ['5. Enforcement', <>We may reject requests, immediately suspend or permanently terminate an account, delete content where permitted, and forfeit unused or remaining credits where we reasonably determine that a user has violated these Terms, attempted to bypass safeguards, created prohibited content, or exposed Gabitor, its users, or the public to harm or legal risk. We may preserve and disclose relevant records when required by law or necessary to protect rights, safety, or security.</>],
  ['6. Your Prompts and Generated Content', <>You remain responsible for the prompts, inputs, and content you submit. Subject to applicable law and third-party rights, you may use generated content for lawful purposes. AI output may be inaccurate, similar to other outputs, or unavailable; you must review it before relying on or publishing it. Do not submit sensitive personal information unless it is necessary and you have the right to do so.</>],
  ['7. Intellectual Property', <>The Service, including its software, branding, and design, is owned by Gabitor or its licensors and is protected by law. These Terms do not transfer ownership of the Service to you. You receive a limited, revocable right to use the Service according to these Terms.</>],
  ['8. Disclaimers and Liability', <>The Service is provided on an "as is" and "as available" basis. To the maximum extent permitted by law, we disclaim warranties not expressly stated in these Terms. To the maximum extent permitted by law, Gabitor will not be liable for indirect, incidental, special, consequential, or punitive damages arising from use of the Service.</>],
  ['9. Changes and Termination', <>We may update the Service or these Terms. Material changes will be posted here with an updated effective date. You may stop using the Service at any time. We may suspend or terminate access for a violation of these Terms or to protect the Service, users, or our business.</>],
  ['10. Governing Law and Contact', <>These Terms are governed by the laws of the State of Illinois, without regard to conflict-of-law principles. Questions may be sent by mail to K.R.&G.M. CLEANING LLC, 5250 Old Orchard Rd, Suite 300, Skokie, IL 60077-4462, United States.</>]
];

export default function TermsOfService() {
  return <main style={{maxWidth:820,margin:'0 auto',padding:'72px 24px',color:'#edf0ff',lineHeight:1.7}}><a href="/" style={{color:'#b9a7ff',textDecoration:'none'}}>← Back to Gabitor</a><p style={{letterSpacing:'0.14em',fontSize:12,color:'#b9a7ff',marginTop:40}}>GABITOR AI</p><h1 style={{fontSize:48,lineHeight:1.1,margin:'8px 0 12px'}}>Terms of Service</h1><p style={{color:'#aab0c5'}}>Effective date: September 9, 2026</p><p>Please read these Terms carefully before using Gabitor AI.</p>{sections.map(([title,body])=><section key={title} style={{marginTop:34}}><h2 style={{fontSize:23}}>{title}</h2><p>{body}</p></section>)}<p style={{marginTop:48,fontSize:14,color:'#aab0c5'}}>These Terms are a starting point for the current Service. Have a qualified U.S. attorney review them before a commercial launch.</p></main>;
}
